import React from "react";
import { useState } from "react";
import { motion } from "framer-motion";
import Profile from "./profile";
import { useNavigate } from "react-router-dom";
import AdvancedSlider from "./FeaturedVideo";


export default function Home() {
  const [topic, setTopic] = useState("");
  const [hours, setHours] = useState("");
  const [syllabus, setSyllabus] = useState(null);
  const [loading, setLoading] = useState(false);
  const token = localStorage.getItem("token");
  const email = localStorage.getItem("email");
  
  const navigate = useNavigate();
 const handleCourse=async()=>{
  const modules=syllabus.modules
  const res=await fetch("http://localhost:3000/user/generatepdf",{
    method:"POST",
    headers:{
      "Content-Type":"application/json",
      token:token
    },
    body:JSON.stringify({email,topic,hours,modules})
  })
  const data=await res.json();
   if (!res.ok || data.success === false) {
      alert(data.message || "Failed to generate Course");
      
      return;
    }

 }
  const handleGenerate = async () => {
  if (loading) return;
  try {
    setLoading(true);
    const res = await fetch("http://localhost:3000/user/syllabus", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        token: token,
      },
      body: JSON.stringify({ topic, hours }),
    });

    const data = await res.json();

    console.log("SYLLABUS RESPONSE:", data);
    if (!res.ok || data.success === false) {
      alert(data.message || "Failed to generate syllabus");
      setSyllabus(null); // avoid broken state
      return;
    }



    if (!data.modules || data.modules.length === 0) {
      alert("No modules generated");
      setSyllabus(null);
      return;
    }


    setSyllabus({
      topic: topic,
      modules: data.modules,
    });
  } catch (err) {
    console.error("ERROR:", err);
    alert("Server error");
  } finally {
    setLoading(false);
    }
  };

  return (
    <div className="h-screen">
      <div className="max-w-10xl mx-auto bg-white/80 backdrop-blur-xl shadow-2xl overflow-hidden">
        <div className="relative p-2 bg-gradient-to-r from-blue-100 via-white to-blue-100">
          <div className="flex justify-between items-center">
            <div className="flex items-center mt-0">
              <img src="./logo1.png" className="h-30 w-60 mt-0 whover:scale-105 transition"></img>
            </div>

            <div className="flex items-center gap-6 text-gray-700">
              <span className="border-b-2 border-black pb-1">All Courses</span>
              <motion.button
              whileHover={{ scale: 1.02 }}
              className="cursor-pointer" onClick={()=>navigate("/Mycoursepage")}>My Learning</motion.button>
              <Profile/>
            </div>
          </div>



          <p className="text-gray-600 mb-10">
            Free, Instant Courses Generated by AI.
          </p>

          <div className="flex flex-col items-center">
            <input
              type="text"
              placeholder="What do you want to learn today?"
              className="w-full max-w-3xl h-14 px-6 rounded-xl border border-gray-400 shadow-inner focus:outline-none"
              onChange={(e) => setTopic(e.target.value)}
            />
            <br></br>
            <label htmlFor="volume">Duration(in hrs):</label>
            <input
              type="number" id="volume" name="volume" min="0" max="100"
              placeholder="Hours"
              className="max-w-3xl h-10 px-6 rounded-xl border border-gray-400 shadow-inner focus:outline-none"
              onChange={(e) => setHours(e.target.value)}
            />

            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              className="mt-6 px-10 py-3 bg-gradient-to-r from-blue-600 to-blue-500 text-white rounded-xl shadow-lg text-lg"
              onClick={handleGenerate}
            >
              Generate Syllabus
            </motion.button>
            {loading && <p>Generating...</p>}
            {syllabus && (
              <div className="p-6 bg-gradient-to-r from-blue-100 via-white to-blue-100 min-h-screen">
                <div className="max-w-5xl mx-auto bg-white/80 shadow-xl rounded-2xl p-6">
                <h2 className="text-2xl font-bold mb-2">{syllabus.topic}</h2>
                <p className="text-gray-500 mb-6">{syllabus.duration}</p>
                <div className="overflow-x-auto">
                  <table className="w-full border border-gray-300 rounded-lg overflow-hidden">
                    <thead className="bg-gray-200">
                      <tr>
                        <th className="p-3 text-left">Module</th>
                        <th className="p-3 text-left">Lessons</th>
                        <th className="p-3 text-center">Action</th>
                      </tr>
                    </thead>   
        <tbody>
          {syllabus.modules?.map((mod, index) => (
            <tr key={index} className="border-t hover:bg-gray-50">
              <td className="p-4 font-semibold">
                {mod.title}
              </td>
              <td className="p-4">
                <ol className="list-decimal ml-5 space-y-1">
                  {mod.lessons?.map((lesson, i) => (
                    <li key={i} className="flex justify-between items-center">
                      <span>{lesson}</span>

                      <button
                        onClick={() => removeLesson(index, i)}
                        className="text-red-500 hover:text-red-700 text-sm ml-4">
                        Remove
                      </button>
                    </li>
                  ))}
                </ol>
              </td>
              <td className="p-4 text-center">
                <button
                  onClick={() => removeModule(index)}
                  className="px-3 py-1 bg-red-500 text-white rounded-lg hover:bg-red-600">
                  Delete
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>

   
     <motion.button
      whileHover={{ scale: 1.05 }}
      whileTap={{ scale: 0.95 }}
      className="mt-6 px-10 py-3 bg-gradient-to-r from-blue-600 to-blue-500 text-white rounded-xl shadow-lg text-lg"
      onClick={handleCourse}
         >
        Generate Course
        </motion.button>
         </div>
        </div>
      )}


      <p className="text-gray-600 mt-6 text-center max-w-xl">
        Try "Quantum Computing Fundamentals", "Creative Writing", "Data Science with Python", "Start-up Marketing"
      </p>
      <AdvancedSlider/>
    </div>
    </div>
      <div className="max-w-10xl mx-auto px-6 mx-auto bg-white/80 backdrop-blur-xl overflow-hidden relative p-10 bg-gradient-to-r from-blue-100 via-white to-blue-100">
        <h2 className="text-2xl font-semibold mb-8 text-gray-800">
          Why AI CourseLab?
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
          <div className="flex gap-4">
            <div className="text-3xl">📄</div>
            <div>
              <h3 className="font-semibold">Instantly Tailored Curriculum</h3>
              <p className="text-sm text-gray-600">Detailed description of personalization</p>
            </div>
          </div>

          <div className="flex gap-4">
            <div className="text-3xl">📊</div>
            <div>
              <h3 className="font-semibold">Comprehensive Analytics</h3>
              <p className="text-sm text-gray-600">Description of detailed feedback</p>
            </div>
          </div>

          <div className="flex gap-4">
            <div className="text-3xl">🧠</div>
            <div>
              <h3 className="font-semibold">AI Insights</h3>
              <p className="text-sm text-gray-600">Advanced AI-driven recommendations</p>
            </div>
          </div>

          <div className="flex gap-4">
            <div className="text-3xl">📚</div>
            <div>
              <h3 className="font-semibold">Curated Free Resources</h3>
              <p className="text-sm text-gray-600">Descriptions of extra materials</p>
            </div>
          </div>

          <div className="flex gap-4">
            <div className="text-3xl">👥</div>
            <div>
              <h3 className="font-semibold">Community Feedback</h3>
              <p className="text-sm text-gray-600">Community-generated reviews</p>
            </div>
          </div>

          <div className="flex gap-4">
            <div className="text-3xl">📝</div>
            <div>
              <h3 className="font-semibold">Integrated Quizzes</h3>
              <p className="text-sm text-gray-600">Detailed learning checks</p>
            </div>
          </div>
        </div>
      </div>

        <div className="bg-white py-6 flex justify-center gap-8 text-gray-500 text-sm">
          <span>About Us</span>
          <span>API Access</span>
          <span>FAQ</span>
          <span>Contribute Resources</span>
        </div>
      </div>
    </div>
  );
}